"""
    salones = {
        "001": {"nombre": "Salón Dorado",
                "capacidad": 150,
                "ubicacion": "Recoleta",
                "alquiler": 250000,
                "servicios": {"serv1": "Catering",
                              "serv2": "DJ",
                              "serv3": "Decoración"},
                "activo": True},
        "002": {"nombre": "Sky Lounge",
                "capacidad": 200,
                "ubicacion": "Palermoc Soho",
                "alquiler": 300000,
                "servicios": {"serv1": "Luces",
                              "serv2": "Pantalla LED",
                              "serv3": "Bar libre"},
                "activo": True},
        "003": {"nombre": "Espacio Lux",
                "capacidad": 120,
                "ubicacion": "San Telmo",
                "alquiler": 180000,
                "servicios": {"serv1": "Catering Premium",
                              "serv2": "Iluminación",
                              "serv3": "Escenario"},
                "activo": True},
        "004": {"nombre": "Eventos Plaza",
                "capacidad": 250,
                "ubicacion": "Belgrano",
                "alquiler": 320000,
                "servicios": {"serv1": "Barra",
                              "serv2": "Fotocabina",
                              "serv3": "Pantalla gigante"},
                "activo": True},
        "005": {"nombre": "Terraza Río",
                "capacidad": 180,
                "ubicacion": "Puerto Madero",
                "alquiler": 280000,
                "servicios": {"serv1": "Vista al río",
                              "serv2": "DJ residente",
                              "serv3": "Catering marino"},
                "activo": True},
        "006": {"nombre": "Palacio Urbano",
                "capacidad": 300,
                "ubicacion": "Palermo",
                "alquiler": 350000,
                "servicios": {"serv1": "Catering Gourmet",
                              "serv2": "Iluminación inteligente",
                              "serv3": "Escenario principal"},
                "activo": True},
        "007": {"nombre": "Jardines del Lago",
                "capacidad": 220,
                "ubicacion": "Costanera Norte",
                "alquiler": 290000,
                "servicios": {"serv1": "Espacio al aire libre",
                              "serv2": "DJ y sonido envolvente",
                              "serv3": "Catering orgánico"},
                "activo": True},
        "008": {"nombre": "Agora Premium",
                "capacidad": 180,
                "ubicacion": "Villa Urquiza",
                "alquiler": 260000,
                "servicios": {"serv1": "Pantalla LED 4K",
                              "serv2": "Servicio de barra",
                              "serv3": "Fotocabina"},
                "activo": True},
        "009": {"nombre": "Luna Park View",
                "capacidad": 400,
                "ubicacion": "Microcentro",
                "alquiler": 400000,
                "servicios": {"serv1": "Catering internacional",
                              "serv2": "Escenario giratorio",
                              "serv3": "DJ residente"},
                "activo": True},
        "010": {"nombre": "Bahia Lounge",
                "capacidad": 150,
                "ubicacion": "Puerto Madero",
                "alquiler": 310000,
                "servicios": {"serv1": "Vista panoramica al rio",
                              "serv2": "Bar libre",
                              "serv3": "Pantalla gigante"},
                "activo": True}
    }

    bandas = {
        "001": {"nombre": "Mordecai y los Rigbys",
                "genero": "Rock",
                "costo_media_hora": 80000,
                "integrantes": {"int1": "Cantante",
                                "int2": "Guitarrista",
                                "int3": "Bajista",
                                "int4": "Baterista"},
                "activo": True},
        "002": {"nombre": "JazzVibes",
                "genero": "Jazz",
                "costo_media_hora": 70000,
                "integrantes": {"int1": "Saxofonista",
                                "int2": "Pianista",
                                "int3": "Contrabajista",
                                "int4": "Baterista"},
                "activo": True},
        "003": {"nombre": "PopZzzone",
                "genero": "Pop",
                "costo_media_hora": 60000,
                "integrantes": {"int1": "Vocalista",
                                "int2": "Tecladista",
                                "int3": "Bajista",
                                "int4": "Baterista"},
                "activo": True},
        "004": {"nombre": "Electronics Bit",
                "genero": "Electrónica",
                "costo_media_hora": 90000,
                "integrantes": {"int1": "DJ",
                                "int2": "Percusionista",
                                "int3": "Técnico de sonido"},
                "activo": True},
        "005": {"nombre": "Salsa Mamma mia",
                "genero": "Salsa",
                "costo_media_hora": 75000,
                "integrantes": {"int1": "Cantante",
                                "int2": "Pianista",
                                "int3": "Percusionista",
                                "int4": "Bajista"},
                "activo": True},
        "006": {"nombre": "Midnight Riders",
                "genero": "Rock",
                "costo_media_hora": 45000,
                "integrantes": {"int1": "Guitarrista",
                                "int2": "Bajo y teclado",
                                "int3": "Vocalista y Ritmo",
                                "int4": "Baterista"},
                "activo": True},
        "007": {"nombre": "Asspera",
                "genero": "Rock bizarro",
                "costo_media_hora": 69000,
                "integrantes": {"int1": "Vocalista",
                                "int2": "Bajo y teclado",
                                "int3": "Gitarrista",
                                "int4": "Bajista"},
                "activo": True},
        "008": {"nombre": "Vocaloid",
                "genero": "JPOP",
                "costo_media_hora": 91000,
                "integrantes": {"int1": "Vocalista 1",
                                "int2": "Vocalista 2",
                                "int3": "Vocalista 3",
                                "int4": "Instrumental"},
                "activo": True},
        "009": {"nombre": "Tan Bionica",
                "genero": "Pop Alternado",
                "costo_media_hora": 76000,
                "integrantes": {"int1": "Voz Principal",
                                "int2": "Gitarrista",
                                "int3": "Baterista",
                                "int4": "Teclado"},
                "activo": True},
        "010": {"nombre": "Los Wachiturros",
                "genero": "Cumbia Villera",
                "costo_media_hora": 23000,
                "integrantes": {"int1": "Baterista",
                                "int2": "Tecladista",
                                "int3": "Vocalista",
                                "int4": "Voz Principal"},
                "activo": True}
    }

    # Diccionario donde se guardarán los eventos
    eventos = {
        "E001": {
            "fecha_hora": "2025.11.15 20:00:00",
            "codigo_salon": "001",            # Salón Dorado
            "codigo_banda": "001",            # Mordecai y los Rigbys
            "duracion_horas": 3,
            "costo_total": bandas["001"]["costo_media_hora"] * (3 * 2)   # 3 horas → 6 medias horas
        },
        "E002": {
            "fecha_hora": "2025.11.18 22:30:00",
            "codigo_salon": "004",            # Eventos Plaza
            "codigo_banda": "004",            # Electronics Bit
            "duracion_horas": 2.5,
            "costo_total": bandas["004"]["costo_media_hora"] * (2.5 * 2)
        },
        "E003": {
            "fecha_hora": "2025.10.05 19:15:00",
            "codigo_salon": "010",            # Bahía Lounge
            "codigo_banda": "009",            # Tan Biónica
            "duracion_horas": 4,
            "costo_total": bandas["009"]["costo_media_hora"] * (4 * 2)
        }
    }
    """